"function"!==typeof Object.create&&(Object.create=function(b){function d(){}d.prototype=b;return new d});
(function(b,d,f,g){var e={init:function(a,c){b("body").removeClass("coda-slider-no-js");b(".coda-slider").prepend('<p class="loading">Loading...<br /><img src="./img/ajax-loader.gif" width="220" height="19" alt="loading..." /></p>');this.elem=c;this.$elem=b(c);this.sliderId="#"+this.$elem.attr("id");this.options=b.extend({},b.fn.codaSlider.options,a);this.sliderId="#"+this.$elem.attr("id");this.build();this.options.autoSlide&&this.autoSlide();this.events();b("p.loading").remove()},build:function(){"coda-slider-wrapper"!=
b(this.sliderId).parent().attr("class")&&b(this.sliderId).wrap('<div id="'+this.$elem.attr("id")+'-wrapper" class="coda-slider-wrapper"></div>');b(this.sliderId+" > div").addClass("panel");this.panelClass=this.sliderId+" .panel";b(this.panelClass).wrapAll('<div class="panel-container"></div>');"panel-wrapper"!=b(this.panelClass).children().attr("class")&&b(this.panelClass).wrapInner('<div class="panel-wrapper"></div>');this.panelContainer=b(this.panelClass).parent();this.options.hashLinking&&(this.hash=
d.location.hash,this.hashPanel=this.hash.replace("#",""));this.currentTab=this.options.hashLinking&&this.hash?this.hashPanel-1:this.options.firstPanelToLoad-1;this.options.autoHeight&&b(this.sliderId).css("height",b(b(this.panelContainer).children()[this.currentTab]).height()+b(this.sliderId+"-wrapper .coda-nav-right").height());this.options.dynamicTabs&&this.addNavigation();this.options.dynamicArrows&&this.addArrows();this.totalSliderWidth=b(this.sliderId).outerWidth(!0)+b(b(this.sliderId).parent()).children("[class^=coda-nav-left]").outerWidth(!0)+
b(b(this.sliderId).parent()).children("[class^=coda-nav-right]").outerWidth(!0);b(b(this.sliderId).parent()).css("width",this.totalSliderWidth);this.options.dynamicTabs&&this.alignNavigation();this.options.continuous&&(b(this.panelContainer).prepend(b(this.panelContainer).children().last().clone()),b(this.panelContainer).append(b(this.panelContainer).children().eq(1).clone()));this.clickable=!0;this.panelCount=b(this.panelClass).length;this.panelWidth=b(this.panelClass).outerWidth();this.totalWidth=
this.panelCount*this.panelWidth;this.pSign="px";this.slideWidth=b(this.sliderId).width();b(this.panelContainer).css("margin-left",-this.slideWidth*~~this.options.continuous+-this.slideWidth*this.currentTab);this.setCurrent(this.currentTab);b(this.sliderId+" .panel-container").css("width",this.totalWidth)},addNavigation:function(){var a=this;"bottom"===a.options.dynamicTabsPosition?b(a.sliderId).after('<div class="coda-nav"><ul></ul></div>'):b(a.sliderId).before('<div class="coda-nav"><ul></ul></div>');
b.each(a.$elem.find(a.options.panelTitleSelector),function(c){b(b(a.sliderId).parent()).find(".coda-nav ul").append('<li class="tab'+(c+1)+'"><a href="#'+(c+1)+'" title="'+b(this).text()+'">'+b(this).text()+"</a></li>")})},alignNavigation:function(){var a=this;a.totalNavWidth=0;var c="";a.options.dynamicArrowsGraphical&&(c="-arrow");"center"!=a.options.dynamicTabsAlign?(b(b(a.sliderId).parent()).find(".coda-nav ul").css("margin-"+a.options.dynamicTabsAlign,b(b(a.sliderId).parent()).find(".coda-nav-"+
a.options.dynamicTabsAlign+c).outerWidth(!0)+parseInt(b(a.sliderId).css("margin-"+a.options.dynamicTabsAlign),10)),b(b(a.sliderId).parent()).find(".coda-nav ul").css("float",a.options.dynamicTabsAlign)):(b(b(a.sliderId).parent()).find(".coda-nav li a").each(function(){a.totalNavWidth+=b(this).outerWidth(!0)}),b(b(a.sliderId).parent()).find(".coda-nav ul").css("width",a.totalNavWidth+41))},addArrows:function(){b(this.sliderId).parent().addClass("arrows");this.options.dynamicArrowsGraphical?(b(this.sliderId).before('<div class="coda-nav-left-arrow" data-dir="prev" title="Slide left"><a href="#"></a></div>'),
b(this.sliderId).after('<div class="coda-nav-right-arrow" data-dir="next" title="Slide right"><a href="#"></a></div>')):(b(this.sliderId).before('<div class="coda-nav-left" data-dir="prev" title="Slide left"><a href="#">'+this.options.dynamicArrowLeftText+"</a></div>"),b(this.sliderId).after('<div class="coda-nav-right" data-dir="next" title="Slide right"><a href="#">'+this.options.dynamicArrowRightText+"</a></div>"))},events:function(){var a=this;b(b(a.sliderId).parent()).find("[class^=coda-nav-]").on("click",
function(c){if(!a.clickable&&a.options.continuous)return!1;a.setCurrent(b(this).attr("class").split("-")[2]);a.options.continuous&&(a.clickable=!1);return!1});b(b(a.sliderId).parent()).find("[class^=coda-nav] li").on("click",function(c){if(!a.clickable&&a.options.continuous)return!1;a.setCurrent(parseInt(b(this).attr("class").split("tab")[1],10)-1);a.options.continuous&&(a.clickable=!1);return!1});b("[data-ref*="+a.sliderId.split("#")[1]+"]").on("click",function(c){if(!a.clickable&&a.options.continuous)return!1;
if(a.options.autoSlideControls){if("stop"===b(this).attr("name"))return b(this).html(a.options.autoSlideStartText).attr("name","start"),clearTimeout(a.autoslideTimeout),!1;if("start"===b(this).attr("name"))return b(this).html(a.options.autoSlideStopText).attr("name","stop"),a.setCurrent(a.currentTab+1),a.autoSlide(),!1}a.setCurrent(parseInt(b(this).attr("href").split("#")[1]-1,10));a.options.continuous&&(a.clickable=!1);a.options.autoSlideStopWhenClicked&&clearTimeout(a.autoslideTimeout);return!1});
b(b(a.sliderId).parent()).find("*").on("click",function(c){a.options.autoSlideControls&&a.options.autoSlideStopWhenClicked&&(b("body").find("[data-ref*="+a.sliderId.split("#")[1]+"][name=stop]").html(a.options.autoSlideStartText),clearTimeout(a.autoslideTimeout));if(!a.clickable&&a.options.continuous)return a.options.autoSlideStopWhenClicked&&clearTimeout(a.autoslideTimeout),!1;a.options.autoSlide&&(a.options.autoSlideStopWhenClicked?clearTimeout(a.autoslideTimeout):(a.autoSlide(clearTimeout(a.autoslideTimeout)),
a.clickable=!0));a.options.continuous&&clearTimeout(a.continuousTimeout)})},setCurrent:function(a){this.clickable&&("number"==typeof a?this.currentTab=a:(this.currentTab+=~~("right"===a)||-1,this.options.continuous||(this.currentTab=0>this.currentTab?this.panelCount-1:this.currentTab%this.panelCount)),this.options.continuous?(this.panelHeightCount=this.currentTab+1,this.setTab=this.currentTab===this.panelCount-2?0:-1===this.currentTab?this.panelCount-3:this.currentTab):this.setTab=this.panelHeightCount=
this.currentTab,b(b(this.sliderId).parent()).find(".tab"+(this.setTab+1)+" a:first").addClass("current").parent().siblings().children().removeClass("current"),this.options.hashLinking&&(d.location.hash=this.options.continuous?this.currentTab===this.panelCount-2?1:-1===this.currentTab?this.panelCount-2:this.currentTab+1:this.currentTab+1),this.transition())},transition:function(){this.options.autoHeight&&b(this.panelContainer).parent().animate({height:b(b(this.panelContainer).children()[this.panelHeightCount]).height()},
{easing:this.options.autoHeightEaseFunction,duration:this.options.autoHeightEaseDuration,queue:!1});this.marginLeft=this.options.continuous?-(this.currentTab*this.slideWidth)-this.slideWidth:-(this.currentTab*this.slideWidth);this.panelContainer.animate({"margin-left":this.marginLeft+this.pSign},{easing:this.options.slideEaseFunction,duration:this.options.slideEaseDuration,queue:!1,complete:this.continuousSlide(this.options.slideEaseDuration+50)})},autoSlide:function(){var a=this;a.options.autoSlideInterval<
a.options.slideEaseDuration&&(a.options.autoSlideInterval=a.options.slideEaseDuration>a.options.autoHeightEaseDuration?a.options.slideEaseDuration:a.options.autoHeightEaseDuration);a.options.continuous&&(a.clickable=!1);a.autoslideTimeout=setTimeout(function(){a.setCurrent(a.options.autoSliderDirection);a.autoSlide()},a.options.autoSlideInterval)},continuousSlide:function(a){var c=this;c.options.continuous?c.continuousTimeout=setTimeout(function(){c.currentTab===c.panelCount-2?(b(c.panelContainer).css("margin-left",
-c.slideWidth+c.pSign),c.currentTab=0):-1===c.currentTab&&(b(c.panelContainer).css("margin-left",-(c.slideWidth*c.panelCount-2*c.slideWidth)+c.pSign),c.currentTab=c.panelCount-3);c.clickable=!0},a):c.clickable=!0}};b.fn.codaSlider=function(a){return this.each(function(){Object.create(e).init(a,this)})};b.fn.codaSlider.options={autoHeight:!0,autoHeightEaseDuration:1500,autoHeightEaseFunction:"easeInOutExpo",autoSlide:!1,autoSliderDirection:"right",autoSlideInterval:7E3,autoSlideControls:!1,autoSlideStartText:"Start",
autoSlideStopText:"Stop",autoSlideStopWhenClicked:!0,continuous:!0,crossLinking:!0,dynamicArrows:!0,dynamicArrowsGraphical:!0,dynamicArrowLeftText:"&#171; left",dynamicArrowRightText:"right &#187;",dynamicTabs:!0,dynamicTabsAlign:"center",dynamicTabsPosition:"top",externalTriggerSelector:"a.xtrig",firstPanelToLoad:1,hashLinking:!1,panelTitleSelector:"h2.title",slideEaseDuration:1500,slideEaseFunction:"easeInOutExpo"}})(jQuery,window,document);
